
name: contoh2
on:
  push:
    branches:
      - main
    pathes:
      - 'folder1/**'

jobs:
  cek_pushan_folder1_saja:
  steps:
    - name: Cek File di folder1 saja kalau kalau ada yang ditambah atau dimodifikasi
      run: git diff --name-only --diff-filter=d main~ main