
name: contoh2
on:
  push:
    branches:
      - main
    paths:
      - 'folder1/**'

jobs:
  cek_pushan_folder1_saja:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Cek File di folder1 saja kalau kalau ada yang ditambah atau dimodifikasi
        uses: appleboy/ssh-action@master
        run: |
          tes_var=$(echo "{\"server\": [{\"server1\":{\"host\":\"host1\",\"username\":\"username1\"}},{\"server2\":{\"host\":\"host2\",\"username\":\"username2\"}}]}" | jq -r '.kesatu[]')
          for x in $tes_var
            do
              echo $x
            done

          changes=$(git diff --name-only main~ main folder1/)
          for i in $changes
            do
              echo $i
            done

      # - name: Update db
      #   run: |
      #     access_server=$(echo "${{ secrets.SERVER }}" | jq -r '.server[]')
      #     changes=$(git diff --name-only main~ main folder1/)

      #     for s in $access_server
      #       do
      #         with:
      #           host: $s['host']
      #           username: ${{ secrets.VULTR_APPOINTMENT_USERNAME }}
      #           key: ${{ secrets.VULTR_APPOINTMENT_SSH_PRIVATE_KEY }}
      #           password: ${{ secrets.VULTR_APPOINTMENT_PASSWORD }}
      #           port: 9669
      #           script: |
      #             cd /var/www/html/dashboardrsudkayen
      #             git pull origin master
      #             cd /var/www/html/dashboardrsunirmala
      #             git pull origin master
      #             cd /var/www/html/dashboardrsuad
      #             git pull origin master


      # - uses: actions/checkout@v3
      # - name: Show databases
      #   run: mysql -h ${{ secrets.DB_HOSTNAME }} --port 3306 -u${{ secrets.DB_USER }} -p${{ secrets.DB_PASSWORD }} -e "SHOW DATABASES";
      # - name: Run a sample SQL on remote
      #   run: mysql -h ${{ secrets.DB_HOSTNAME }} --port 3306 -u${{ secrets.DB_USER }} -p${{ secrets.DB_PASSWORD }} -e "source hawthorn/hawthorn_script.sql";