name: contoh

on:
  push:
    branches:
      - main

jobs:
  cek_pushan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Modified files
        run: |
          pwd
          git diff --name-only --diff-filter=d main~ main

