name: Test Runner

on:
  push:
    branches:
      - main
    paths:
      - 'sql/**'

jobs:
  cek_pushan:
    runs-on: 
      - self-hosted
      - label-tinkped
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Update SQL di folder sql ke database
        continue-on-error: true
        run: |
          set +e
          curl --location --request POST "https://api.telegram.org/bot${{ secrets.MFANO_TOKEN_BOT }}/sendMessage" --form text="START UPDATE SQL" --form chat_id="${{ secrets.AINUR_TELE_ID }}"
          changes=$(git diff --name-only main~ main sql/)
            for file in $changes
              do
                OUTPUT=$(mysql -N -u ${{ secrets.USERNAME_DATABASE_TINKPED }} -p${{ secrets.PASSWORD_DATABASE_TINKPED }} jenkins_testdb -e "source $file" 2>&1)
                EXIT_CODE=$?
                if [ $EXIT_CODE -eq 0 ]; then curl --location --request POST "https://api.telegram.org/bot${{ secrets.MFANO_TOKEN_BOT }}/sendMessage" --form text="Execute $file Berhasil" --form chat_id="${{ secrets.AINUR_TELE_ID }}"; else curl --location --request POST "https://api.telegram.org/bot${{ secrets.MFANO_TOKEN_BOT }}/sendMessage" --form text="Execute $file GAGAL" --form chat_id="${{ secrets.AINUR_TELE_ID }}"; curl --location --request POST "https://api.telegram.org/bot${{ secrets.MFANO_TOKEN_BOT }}/sendMessage" --form text="$OUTPUT" --form chat_id="${{ secrets.AINUR_TELE_ID }}"; fi
              done

