name: Test Runner

on:
  push:
    branches:
      - main
    paths:
      - 'sql/**'

jobs:
  cek_pushan:
    runs-on: 
      - self-hosted
      - label-tinkped
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Update SQL di folder sql ke database
        run: |
          curl --location --request POST "https://api.telegram.org/bot${{ secrets.MFANO_TOKEN_BOT }}/sendMessage" --form text="START UPDATE SQL" --form chat_id="${{ secrets.AINUR_TELE_ID }}"
          changes=$(git diff --name-only main~ main sql/)
            for file in $changes
              do
                mysql -N -u ${{ secrets.USERNAME_DATABASE_TINKPED }} -p${{ secrets.PASSWORD_DATABASE_TINKPED }} jenkins_testdb -e "source $i"
                curl --location --request POST "https://api.telegram.org/bot${{ secrets.MFANO_TOKEN_BOT }}/sendMessage" --form text="Execute $i" --form chat_id="${{ secrets.AINUR_TELE_ID }}"
              done

