name: Test Runner

on:
  push:
    branches:
      - main
    paths:
      - 'sql/**'

jobs:
  cek_pushan:
    runs-on: 
      - gh-runner-tinkped

    env:
      USER_DB: ${{ secrets.USERNAME_DATABASE_TINKPED }}
      PASS_DB: ${{ secrets.PASSWORD_DATABASE_TINKPED }}

      TOKEN_BOT: ${{ secrets.LOGGITHUBSIMRSBOT }}
      CHAT_IDS: ${{ secrets.TELE_IDS }}

      METADATA_FILE: "metadata_sql.json"
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: '/var/www/html'
          fetch-depth: 0

      - name: Update SQL di folder sql ke database
        continue-on-error: true
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          set +e

          IFS=',' read -r -a chat_ids <<< "$CHAT_IDS"

          for chat_id in "${chat_ids[@]}"; 
          do
            curl --location --request POST "https://api.telegram.org/bot$TOKEN_BOT/sendMessage" --form text="COMMIT $COMMIT_MESSAGE" --form chat_id="$chat_id"
            curl --location --request POST "https://api.telegram.org/bot$TOKEN_BOT/sendMessage" --form text="START UPDATE SQL" --form chat_id="$chat_id"
          done

          changes=$(git diff --name-only main~ main sql/)

          declare -A file_dates
          while IFS="=" read -r key value; 
            do
              key=$(echo "$key" | tr -d ' "')
              value=$(echo "$value" | tr -d ' ",')
              file_dates["$key"]="$value"
            done < <(jq -r 'to_entries[] | "\(.key)=\(.value)"' "$METADATA_FILE")

          sorted_files=()
          for file in $changes; 
            do
              if [[ -n "${file_dates[$file]}" ]]; then
                sorted_files+=("${file_dates[$file]} $file")
              fi
            done

          IFS=$'\n' sorted_files=($(printf "%s\n" "${sorted_files[@]}" | sort))

          for entry in "${sorted_files[@]}";
            do
              file=$(echo "$entry" | awk '{print $2}')
              OUTPUT=$(mysql -N -u $USER_DB -p$PASS_DB jenkins_testdb -e "source $file" 2>&1)
              EXIT_CODE=$?
              for chat_id in "${chat_ids[@]}"; 
                do
                  if [ $EXIT_CODE -eq 0 ]; then curl --location --request POST "https://api.telegram.org/bot$TOKEN_BOT/sendMessage" --form text="Execute $file Berhasil" --form chat_id="$chat_id"; else curl --location --request POST "https://api.telegram.org/bot$TOKEN_BOT/sendMessage" --form text="Execute $file GAGAL" --form chat_id="$chat_id"; curl --location --request POST "https://api.telegram.org/bot$TOKEN_BOT/sendMessage" --form text="$OUTPUT" --form chat_id="$chat_id"; fi
                done
              
            done

